// BracketSim legacy compatibility: Shadowlands soulbind traits.
//
// GENERATED by simc-tests/runeforge/gen_legacy_soulbinds.py - do not hand edit.
//
// Midnight's DBC export drops 127 of these 134 spells, so find_spell() cannot
// reach them and there is no value to read from client data the sim carries.
// The live client still resolves all of them, so the ids, names and fully
// substituted descriptions below were read straight out of the running game
// with BracketSimDump/Deep.lua and are the only source for these effects.
//
// Trustworthy in a way the conduit table is not: conduit values came from the
// deleted ConduitRank table and now resolve to stale numbers or literal zero,
// while soulbind values sit in ordinary spell effects. Every one of the 7
// traits that does survive in the sim's data matches its live description.
//
// Soulbinds have no rank system - a trait is on or it is off - so unlike
// legacy_conduits.hpp there is no rank array here.

#pragma once

#include "config.hpp"

#include <cstddef>
#include <string>
#include <string_view>
#include <unordered_set>
#include <vector>

namespace legacy_soulbind
{
enum covenant_e
{
  COVENANT_NONE = 0,
  COVENANT_KYRIAN = 1,
  COVENANT_VENTHYR = 2,
  COVENANT_NIGHT_FAE = 3,
  COVENANT_NECROLORD = 4,
};

struct entry_t
{
  unsigned spell_id;
  unsigned soulbind_id;
  covenant_e covenant;
  unsigned row;
  const char* name;
  const char* soulbind;
  // The live client's description, numbers already substituted. Kept so a
  // port can be checked against what the game actually says without another
  // trip in game.
  const char* desc;
};

inline const std::vector<entry_t>& table()
{
  static const std::vector<entry_t> t = {
      // Kyrian / Pelagos
      { 328266,  7, COVENANT_KYRIAN   ,  0, "Combat Meditation", "Pelagos",
        "Boon of the Ascended increases your Mastery by 79.4 for 30.0 sec and occasionally expels Sorrowful Memories.  | Walking through Sorrowful Memories extends this effect by 9.0 sec." },
      { 328261,  7, COVENANT_KYRIAN   ,  2, "Focusing Mantra", "Pelagos",
        "Defeating an enemy lowers the cooldown on your Phial of Serenity by 1 sec." },
      { 329786,  7, COVENANT_KYRIAN   ,  2, "Road of Trials", "Pelagos",
        "Defeating an enemy grants you 10% movement speed for 20 sec. This effect is increased if defeating a powerful enemy." },
      { 329777,  7, COVENANT_KYRIAN   ,  2, "Phial of Patience", "Pelagos",
        "Phial of Serenity heals you for 35% additional health, but all of its healing is done over 10 sec." },
      { 328265,  7, COVENANT_KYRIAN   ,  4, "Bond of Friendship", "Pelagos",
        "Defeating an enemy reduces the cooldown on your steward's non-Phial services by 30 sec." },
      { 328263,  7, COVENANT_KYRIAN   ,  4, "Cleansed Vestments", "Pelagos",
        "You have a chance to obtain cleansed cloth and enchanting materials when you kill an enemy that yields experience or honor." },
      { 328257,  7, COVENANT_KYRIAN   ,  7, "Let Go of the Past", "Pelagos",
        "Using a spell or ability reduces your magic damage taken by 1% for 6 sec. Using another spell or ability increases this amount by 1% when it is not a repeat of the previous spell or ability, stacking to 3%." },
      { 351146,  7, COVENANT_KYRIAN   ,  9, "Better Together", "Pelagos",
        "During combat, moving within 3 yd of a party or raid member inspires both of you, increasing Mastery by 10 for 1 min. | Players may only be affected by one such effect." },
      { 351147,  7, COVENANT_KYRIAN   ,  9, "Path of the Devoted", "Pelagos",
        "After recovering from a loss of control effect, you take 20% reduced damage and your movement speed cannot be reduced below 90% for 5 sec. | May only occur once per 30 sec." },
      { 351149,  7, COVENANT_KYRIAN   , 11, "Newfound Resolve", "Pelagos",
        "At any moment during combat, there is a low chance your Doubt will manifest for 10 sec. Directly facing your Doubt will overcome it, granting 10% Intellect and Stamina for 15 sec." },
      // Kyrian / Kleia
      { 329791, 13, COVENANT_KYRIAN   ,  0, "Valiant Strikes", "Kleia",
        "Your critical strikes grant you stacks of Valiant Strikes, up to 20. If a nearby party member drops below 50% health, you consume these stacks to heal them for 1% of their maximum health per stack. | After healing this way, you may not benefit from Valiant Strikes for 1 min." },
      { 334066, 13, COVENANT_KYRIAN   ,  2, "Mentorship", "Kleia",
        "While above 90% health, you increase nearby party members' maximum health by 5%." },
      { 329776, 13, COVENANT_KYRIAN   ,  2, "Ascendant Phial", "Kleia",
        "Phial of Serenity renders you immune to Curse, Disease, Poison, and Bleed effects for 8 sec." },
      { 329784, 13, COVENANT_KYRIAN   ,  4, "Cleansing Rites", "Kleia",
        "After 5 sec out of combat, gain a shield for 10% of your maximum health." },
      { 328258, 13, COVENANT_KYRIAN   ,  4, "Ever Forward", "Kleia",
        "While above 90% health, your mounted movement speed is increased by 10%." },
      { 329779, 13, COVENANT_KYRIAN   ,  7, "Bearer's Pursuit", "Kleia",
        "Your damaging spells and abilities have a chance to decrease your target's movement speed by 45% for 20 sec." },
      { 329778, 13, COVENANT_KYRIAN   ,  7, "Pointed Courage", "Kleia",
        "Chance to critical strike is increased by 2% for every nearby enemy or ally, up to 6%." },
      { 329781, 13, COVENANT_KYRIAN   ,  7, "Resonant Accolades", "Kleia",
        "When receiving healing while above 70% health or healing an ally that's above 70% health, 4% of the healing done is repeated on the target over 5 sec." },
      { 351488, 13, COVENANT_KYRIAN   ,  9, "Spear of the Archon", "Kleia",
        "Movement speed increased by 6% while out of combat. Gain 3% critical strike chance for 10 sec after damaging an enemy above 90% health." },
      { 351489, 13, COVENANT_KYRIAN   ,  9, "Hope Springs Eternal", "Kleia",
        "Your Phial of Serenity reduces damage taken by 20% for 8 sec and its effects are also granted to your lowest-health ally." },
      { 351491, 13, COVENANT_KYRIAN   , 11, "Light the Path", "Kleia",
        "Your Valiant Strikes grant 0.25% critical strike chance per stack. When your Valiant Strikes heals an ally, you each gain 5% critical strike chance for 15 sec." },
      // Kyrian / Forgelite Prime Mikanikos
      { 333950, 18, COVENANT_KYRIAN   ,  0, "Bron's Call to Action", "Forgelite Prime Mikanikos",
        "After using 75 damaging or healing spells and abilities, your next spell or ability summons Bron, who knocks enemies back on arrival and then attacks and heals your targets for 30 sec." },
      { 331609, 18, COVENANT_KYRIAN   ,  2, "Forgelite Filter", "Forgelite Prime Mikanikos",
        "When reduced below 35% health, your Phial of Serenity automatically heals you and consumes a charge." },
      { 331610, 18, COVENANT_KYRIAN   ,  2, "Charged Additive", "Forgelite Prime Mikanikos",
        "Phial of Serenity also knocks nearby enemies away from you." },
      { 331726, 18, COVENANT_KYRIAN   ,  4, "Regenerating Materials", "Forgelite Prime Mikanikos",
        "Casting or receiving healing has a chance to improve the remaining durability on your armor." },
      { 331725, 18, COVENANT_KYRIAN   ,  4, "Resilient Plumage", "Forgelite Prime Mikanikos",
        "Fall damage decreased by 20%, and after taking fall damage, damage you take is reduced by 20% for 15 sec." },
      { 331611, 18, COVENANT_KYRIAN   ,  7, "Soulsteel Clamps", "Forgelite Prime Mikanikos",
        "After 5 sec standing still, incoming stun and incapacitate durations are reduced by 15%. Lasts for 5 sec once you start moving." },
      { 333935, 18, COVENANT_KYRIAN   ,  7, "Hammer of Genesis", "Forgelite Prime Mikanikos",
        "Damaging a new enemy grants you 3% Haste for 10 sec, up to 5 stacks." },
      { 331612, 18, COVENANT_KYRIAN   ,  7, "Sparkling Driftglobe Core", "Forgelite Prime Mikanikos",
        "When reduced below 30% health, you stun nearby enemies for 3 sec. This effect may only occur once every 60 sec." },
      { 352186, 18, COVENANT_KYRIAN   ,  9, "Soulglow Spectrometer", "Forgelite Prime Mikanikos",
        "Damaging or healing a target analyzes its merit over 15 sec, increasing your damage or healing to it by 1%, increasing by an additional 1% every 3 sec. | Cannot start a new analysis of each type until the previous one has finished." },
      { 352187, 18, COVENANT_KYRIAN   ,  9, "Reactive Retrofitting", "Forgelite Prime Mikanikos",
        "After taking Physical or Magic damage, gain a shield that absorbs damage equal to 6% of your maximum Health for 10 sec. | Each incoming damage type may trigger this effect once per 30 sec." },
      { 352188, 18, COVENANT_KYRIAN   , 11, "Effusive Anima Accelerator", "Forgelite Prime Mikanikos",
        "Boon of the Ascended releases a blast of overcharged anima at your target's location, dealing 3,469 Arcane damage split evenly between all targets over 8 sec. | Reduce the cooldown of Boon of the Ascended by 12 sec per affected enemy, to a maximum of 60 sec." },
      // Venthyr / General Draven
      { 340159,  3, COVENANT_VENTHYR  ,  0, "Service In Stone", "General Draven",
        "Damage taken below 40% health is reduced by 10%. Upon death you leave a stone husk behind which shatters after 3 sec, inflicting 100% of your maximum health in Physical damage split among nearby enemies, and healing for 100% of your maximum health split among allies within 20 yds." },
      { 319982,  3, COVENANT_VENTHYR  ,  2, "Move As One", "General Draven",
        "When a nearby ally gains temporary increased movement speed, you also gain the benefit, up to 30% for 8 sec." },
      { 319978,  3, COVENANT_VENTHYR  ,  2, "Enduring Gloom", "General Draven",
        "Door of Shadows grants you a shield that absorbs damage equal to 20% of your maximum health. Lasts 8 sec." },
      { 332755,  3, COVENANT_VENTHYR  ,  4, "Unbreakable Body", "General Draven",
        "Your equipment takes 50% less durability damage from death." },
      { 332756,  3, COVENANT_VENTHYR  ,  4, "Expedition Leader", "General Draven",
        "Leaving a resting area increases your mounted speed by 10%, and your out of combat regeneration by 100%. Lasts 10 min, and completing a World Quest refreshes the duration." },
      { 332754,  3, COVENANT_VENTHYR  ,  7, "Hold Your Ground", "General Draven",
        "Standing still for at least 4 sec grants you 10% increased Stamina, and 4% increased healing done. This effect persists for 6 sec after you start moving." },
      { 332753,  3, COVENANT_VENTHYR  ,  7, "Superior Tactics", "General Draven",
        "Successfully interrupting an enemy or dispelling an ally increases your critical strike chance by 10% for 10 sec. This may only occur once every 30 sec." },
      { 319973,  3, COVENANT_VENTHYR  ,  7, "Built for War", "General Draven",
        "While you are above 80% health you gain 1% Intellect every 2 sec, stacking up to 5 times. If you fall below 50% health, this effect is lost." },
      { 352365,  3, COVENANT_VENTHYR  ,  9, "Regenerative Stone Skin", "General Draven",
        "Any overhealing done to you will heal for an additional 15% of the overhealing amount over 6 sec." },
      { 352415,  3, COVENANT_VENTHYR  ,  9, "Intimidation Tactics", "General Draven",
        "While below 50% health, Door of Shadows cools down 200% faster." },
      { 352417,  3, COVENANT_VENTHYR  , 11, "Battlefield Presence", "General Draven",
        "Each nearby enemy trembles at your presence, increasing your damage and healing done by 1%, and reducing damage taken by 1%, up to a maximum of 3 enemies." },
      // Venthyr / Nadjia the Mistblade
      { 331586,  8, COVENANT_VENTHYR  ,  0, "Thrill Seeker", "Nadjia the Mistblade",
        "While in combat, you gain a stack of Thrill Seeker every 2 sec, or 4 stacks on killing an enemy. At 40 stacks Thrill Seeker is consumed to grant you Euphoria, increasing your Haste by 20% for 10 sec. Thrill Seeker decays rapidly while you are not in combat." },
      { 331576,  8, COVENANT_VENTHYR  ,  2, "Agent of Chaos", "Nadjia the Mistblade",
        "Door of Shadows disorients all nearby enemies at the target location for 6 sec when you appear." },
      { 331577,  8, COVENANT_VENTHYR  ,  2, "Fancy Footwork", "Nadjia the Mistblade",
        "Door of Shadows increases your movement speed by 40%, decaying over 6 sec." },
      { 331579,  8, COVENANT_VENTHYR  ,  4, "Friends in Low Places", "Nadjia the Mistblade",
        "You loot 20% more Infused Rubies, and dredgers throughout Revendreth offer you an expanded selection of goods." },
      { 331582,  8, COVENANT_VENTHYR  ,  7, "Familiar Predicaments", "Nadjia the Mistblade",
        "The duration of incoming interrupt, snare, and root effects are reduced by 15%." },
      { 331580,  8, COVENANT_VENTHYR  ,  7, "Exacting Preparation", "Nadjia the Mistblade",
        "The benefits of Well Fed, Flask, and weapon enchant effects are increased by 20%." },
      { 331584,  8, COVENANT_VENTHYR  ,  7, "Dauntless Duelist", "Nadjia the Mistblade",
        "The first enemy you damage in combat is marked as your Adversary. You deal 3% more damage to them, and they deal 1.5% less damage to you. You may only have one Adversary at a time." },
      { 352405,  8, COVENANT_VENTHYR  ,  9, "Sinful Preservation", "Nadjia the Mistblade",
        "Health Potions and Healthstones grant you an absorb shield equal to 50% of the amount healed for 20 sec." },
      { 352366,  8, COVENANT_VENTHYR  ,  9, "Nimble Steps", "Nadjia the Mistblade",
        "Enemies within 8 yds are slowed by 10%. If you fall below 35% health, enemies within 8 yds are rooted for 4 sec. This can only occur once every 60 sec." },
      { 352373,  8, COVENANT_VENTHYR  , 11, "Fatal Flaw", "Nadjia the Mistblade",
        "When the Haste effect of Euphoria ends, gain 10 sec of either 20% increased Critical Strike chance or Versatility, whichever you currently have more of." },
      // Venthyr / Theotar the Mad Duke
      { 336239,  9, COVENANT_VENTHYR  ,  0, "Soothing Shade", "Theotar the Mad Duke",
        "Your spells and abilities have a chance to call Tubbins and Gubbins to your side for 12 sec, parasol in hand. Standing in the shaded area grants you 138 Mastery." },
      { 336140,  9, COVENANT_VENTHYR  ,  2, "Watch the Shoes!", "Theotar the Mad Duke",
        "Door of Shadows frees you from roots and snares." },
      { 336147,  9, COVENANT_VENTHYR  ,  2, "Leisurely Gait", "Theotar the Mad Duke",
        "Door of Shadows has 2 charges, but its cooldown is increased by 30 sec." },
      { 336247,  9, COVENANT_VENTHYR  ,  4, "Life of the Party", "Theotar the Mad Duke",
        "During the Ember Court, your Guests gain additional Happiness for each event completed. When the Court concludes, the effects of any Decrees bestowed upon you are increased." },
      { 336184,  9, COVENANT_VENTHYR  ,  4, "Exquisite Ingredients", "Theotar the Mad Duke",
        "You have a chance to obtain an assortment of flavorful herbs and beverages when you kill an enemy that yields experience or honor." },
      { 336245,  9, COVENANT_VENTHYR  ,  7, "Token of Appreciation", "Theotar the Mad Duke",
        "Grant a shield that absorbs 635 damage to allies who aid you with healing or beneficial magic effects. You will only shield each ally once every 20 sec." },
      { 336243,  9, COVENANT_VENTHYR  ,  7, "Refined Palate", "Theotar the Mad Duke",
        "The effects of combat potions last 100% to 200% longer." },
      { 319983,  9, COVENANT_VENTHYR  ,  7, "Wasteland Propriety", "Theotar the Mad Duke",
        "Mindgames signals the start of tea time, granting 6% Versatility to you and 3% Versatility to up to 4 nearby allies. Lasts 8 sec." },
      { 351747,  9, COVENANT_VENTHYR  ,  9, "It's Always Tea Time", "Theotar the Mad Duke",
        "When Soothing Shade activates, Tubbins and Gubbins each offer you a cup of tea, healing you for 231 health every 1 sec and reducing damage taken by 5% while standing in the shaded area." },
      { 351748,  9, COVENANT_VENTHYR  ,  9, "Life is but an Appetizer", "Theotar the Mad Duke",
        "While you are Well Fed, gain 15 Speed and 15 Avoidance." },
      { 351750,  9, COVENANT_VENTHYR  , 11, "Party Favors", "Theotar the Mad Duke",
        "Speak with Theotar in Sinfall to obtain The Mad Duke's Tea. | Drinking The Mad Duke's Tea increases your Haste, Versatility, Critical Strike Chance, or Intellect for 4 |4hour:hrs;. | You can only have the effects of one of The Mad Duke's Tea at a time." },
      // Night Fae / Niya
      { 322721,  1, COVENANT_NIGHT_FAE,  0, "Grove Invigoration", "Niya",
        "Healing or dealing damage has a chance to grant you a stack of Redirected Anima. Redirected Anima increases your maximum health by 1% and your Mastery by 6 for 30 sec, and stacks overlap. | Fae Guardians grants you 12 stacks of Redirected Anima." },
      { 342270,  1, COVENANT_NIGHT_FAE,  2, "Run Without Tiring", "Niya",
        "While in Soulshape, you regenerate 5% of your maximum health every 3 sec." },
      { 320658,  1, COVENANT_NIGHT_FAE,  2, "Stay on the Move", "Niya",
        "Soulshape's cooldown is reduced by 15 sec, and defeating an enemy reduces Soulshape's cooldown by 1 sec." },
      { 320668,  1, COVENANT_NIGHT_FAE,  4, "Nature's Splendor", "Niya",
        "You have a chance to obtain leather, meat, and fish when you kill an enemy that yields experience or honor." },
      { 320687,  1, COVENANT_NIGHT_FAE,  4, "Swift Patrol", "Niya",
        "Movement speed increased by 20% for 2 min after defeating an enemy. Combat cancels this effect." },
      { 320659,  1, COVENANT_NIGHT_FAE,  7, "Niya's Tools: Burrs", "Niya",
        "Your damaging attacks and spells have a chance to toss Niya's Spiked Burrs under your target. The burrs latch onto the first enemy to cross them, reducing movement speed by 20% and inflicting 841 Nature damage over 6 sec." },
      { 320660,  1, COVENANT_NIGHT_FAE,  7, "Niya's Tools: Poison", "Niya",
        "Your interrupts apply Niya's Paralytic Poison to your target, dealing 635 Nature damage over 30 sec. Targets with Niya's Paralytic Poison take an additional 102 Nature damage if interrupted once more." },
      { 320662,  1, COVENANT_NIGHT_FAE,  7, "Niya's Tools: Herbs", "Niya",
        "Your healing spells and abilities have a chance to apply Niya's Invigorating Herbs, increasing the target's Haste by 5% for 10 sec." },
      { 352501,  1, COVENANT_NIGHT_FAE,  9, "Called Shot", "Niya",
        "When you critically strike, you gain 20% movement speed for 5 sec. | May only occur once every 10 sec." },
      { 352502,  1, COVENANT_NIGHT_FAE,  9, "Survivor's Rally", "Niya",
        "When you fall below 50% health, you regain 20% of your health over 10 sec and receive 10% additional healing from other spells and abilities. | May only occur once every 60 sec." },
      { 352503,  1, COVENANT_NIGHT_FAE, 11, "Bonded Hearts", "Niya",
        "Gaining a stack of Redirected Anima from Grove Invigoration heals up to 5 nearby allies for 2% of their health, up to a maximum of 2,000 health. If any of the affected allies are of another covenant, Redirected Anima's Mastery and maximum health effects are increased by 50% for 5 sec." },
      // Night Fae / Dreamweaver
      { 319217,  2, COVENANT_NIGHT_FAE,  0, "Podtender", "Dreamweaver",
        "When you take damage that would kill you, instead rejuvenate within a wildseed, regaining 30% of HP over 10 sec. If the wildseed takes more than 4,010 damage during this time, you die. | This effect may only occur once every 10 min." },
      { 319211,  2, COVENANT_NIGHT_FAE,  3, "Soothing Voice", "Dreamweaver",
        "When your roots, stuns, and incapacitating class effects expire or are dispelled, your target's movement speed is reduced by 90%, decaying rapidly over 2 sec." },
      { 319210,  2, COVENANT_NIGHT_FAE,  3, "Social Butterfly", "Dreamweaver",
        "When at least 2 allies are within 8 yd, your Versatility increases by 3% for 5 sec. When this expires, 2 nearby allies gain 33% of this effect for 5 sec before passing it back to you." },
      { 319213,  2, COVENANT_NIGHT_FAE,  3, "Empowered Chrysalis", "Dreamweaver",
        "10% of your overhealing received or done remains as a shield on the target up to 10% of the caster's health, lasting for 5 sec." },
      { 319214,  2, COVENANT_NIGHT_FAE,  6, "Faerie Dust", "Dreamweaver",
        "When falling farther than 20 yd, faerie dust slows your fall for the next 30 sec. This cannot occur more often than once per 1 min." },
      { 319216,  2, COVENANT_NIGHT_FAE,  6, "Somnambulist", "Dreamweaver",
        "After spending 60 sec in a rested area, you gain 20% increased movement speed for 30 min." },
      { 319191,  2, COVENANT_NIGHT_FAE,  7, "Field of Blossoms", "Dreamweaver",
        "Fae Guardians puts flowers at your feet for 18.0 sec that increase your Haste by 15% while you stand with them." },
      { 352782,  2, COVENANT_NIGHT_FAE,  9, "Cunning Dreams", "Dreamweaver",
        "Soulshape and Flicker slow enemies near your starting point by 50% for 6 sec." },
      { 352779,  2, COVENANT_NIGHT_FAE,  9, "Waking Dreams", "Dreamweaver",
        "When you take damage below 80% health, you gain a shield for 20% of your maximum health for 12 sec. | This can only occur once every 1 min." },
      { 352786,  2, COVENANT_NIGHT_FAE, 11, "Dream Delver", "Dreamweaver",
        "Dealing damage or healing a target grants you 1% increased damage or healing to that target for 4 sec, up to 3%." },
      // Night Fae / Korayn
      { 325066,  6, COVENANT_NIGHT_FAE,  0, "Wild Hunt Tactics", "Korayn",
        "Your damage to targets above 75% health and healing to targets below 35% health is increased by 10%. | When your spells and abilities are enhanced this way, you gain 15% increased movement speed for 5 sec." },
      { 325067,  6, COVENANT_NIGHT_FAE,  2, "Horn of the Wild Hunt", "Korayn",
        "Soulshape increases the movement speed of allies within 40 yds by 10%." },
      { 325065,  6, COVENANT_NIGHT_FAE,  2, "Wild Hunt's Charge", "Korayn",
        "While out of combat, your Soulshape's teleport becomes a charge, stunning your target for 5 sec and ending your Soulshape." },
      { 325072,  6, COVENANT_NIGHT_FAE,  4, "Vorkai Sharpening Techniques", "Korayn",
        "Your weapon takes no durability damage." },
      { 325073,  6, COVENANT_NIGHT_FAE,  4, "Get In Formation", "Korayn",
        "Your mounted movement speed is increased by 5%. Allies behind you within 40 yds gain this benefit." },
      { 325068,  6, COVENANT_NIGHT_FAE,  7, "Face Your Foes", "Korayn",
        "When in front of your target, your spells and abilities decrease the damage they inflict on you by 3% for 2 sec." },
      { 325069,  6, COVENANT_NIGHT_FAE,  7, "First Strike", "Korayn",
        "Damaging an enemy before they damage you increases your chance to critical strike by 25% for 5 sec." },
      { 325601,  6, COVENANT_NIGHT_FAE,  7, "Hold the Line", "Korayn",
        "After standing still for 5 sec, you take 12% less Physical damage until you move." },
      { 352800,  6, COVENANT_NIGHT_FAE,  9, "Vorkai Ambush", "Korayn",
        "After interrupting or disorienting an enemy, they deal 5% less damage for 5 sec." },
      { 352806,  6, COVENANT_NIGHT_FAE,  9, "Hunt's Exhilaration", "Korayn",
        "When damaging an enemy or healing an ally within 8 yds, you gain 3% Leech for 5 sec." },
      { 352805,  6, COVENANT_NIGHT_FAE, 11, "Wild Hunt Strategem", "Korayn",
        "When your damage or healing is enhanced by Wild Hunt Tactics, gain Wild Hunt Strategem for 1 min.  | The next time you damage an enemy who is below 35% health, or heal an ally who is above 75% health, Wild Hunt Strategem is activated to increase your damage and healing to such targets by 5% for 10 sec." },
      // Necrolord / Plague Deviser Marileth
      { 323074,  4, COVENANT_NECROLORD,  0, "Volatile Solvent", "Plague Deviser Marileth",
        "Fleshcraft's passive effect consumes a corpse's essence completely, granting a benefit based on the creature's type.  | Casting Fleshcraft also consumes a small portion of your own essence, granting you the Humanoid benefit." },
      { 323091,  4, COVENANT_NECROLORD,  2, "Ooz's Frictionless Coating", "Plague Deviser Marileth",
        "When reduced below 50% health, Ooz courses over you, granting you a shield for 15% of your maximum health for 10 sec. May only occur once per 30 sec." },
      { 323089,  4, COVENANT_NECROLORD,  2, "Travel with Bloop", "Plague Deviser Marileth",
        "While standing still, you slowly build stacks of Bloop's Wanderlust. At 5 stacks, your movement speed is increased by 10% for 2 min." },
      { 323090,  4, COVENANT_NECROLORD,  2, "Plaguey's Preemptive Strike", "Plague Deviser Marileth",
        "Your first attack or spell cast on an enemy increases your damage done to them by 12% for 15 sec. Limit 1." },
      { 323079,  4, COVENANT_NECROLORD,  4, "Kevin's Keyring", "Plague Deviser Marileth",
        "Allows opening of locks that require up to 60 skill, once every 12 hours. | Each 1 sec spent channeling Fleshcraft reduces Kevin's Keyring's cooldown by 60 min." },
      { 323081,  4, COVENANT_NECROLORD,  4, "Plagueborn Cleansing Slime", "Plague Deviser Marileth",
        "Defeating enemies has a chance to deploy your Plagueborn Cleansing Slime, which improves the remaining durability on your armor." },
      { 323095,  4, COVENANT_NECROLORD,  7, "Ultimate Form", "Plague Deviser Marileth",
        "While channeling Fleshcraft, you are immune to crowd control and you regenerate 2% health every 1 sec.  | If you finish the full channel, you gain 3 sec of crowd control immunity, during which you regenerate 2% health every 1 sec." },
      { 352108,  4, COVENANT_NECROLORD,  9, "Viscous Trail", "Plague Deviser Marileth",
        "When struck by a snare, you drop a puddle that lasts for 10 sec. Enemies that step in the puddle are slowed by 70% for 5 sec. | May only occur once every 60 sec." },
      { 352109,  4, COVENANT_NECROLORD,  9, "Undulating Maneuvers", "Plague Deviser Marileth",
        "While above 80% health, 5% of damage taken is absorbed and spread out over 5 sec." },
      { 352110,  4, COVENANT_NECROLORD, 11, "Kevin's Oozeling", "Plague Deviser Marileth",
        "Unholy Nova summons Kevin's Oozeling to fight alongside you for 20.0 sec. His attacks cause your enemies to take 6% additional damage from you and he periodically grants your allies an absorb shield that absorbs 42 damage." },
      // Necrolord / Emeni
      { 342156,  5, COVENANT_NECROLORD,  0, "Lead by Example", "Emeni",
        "Unholy Nova increases your Intellect by 5% and up to 4 nearby allies' primary stat by 2% for 10.0 sec. You gain 2% additional Intellect for each ally affected." },
      { 323921,  5, COVENANT_NECROLORD,  2, "Emeni's Magnificent Skin", "Emeni",
        "Fleshcraft increases your maximum health by 5% for 30 sec." },
      { 341650,  5, COVENANT_NECROLORD,  2, "Emeni's Ambulatory Flesh", "Emeni",
        "You may channel Fleshcraft while moving." },
      { 324440,  5, COVENANT_NECROLORD,  4, "Cartilaginous Legs", "Emeni",
        "After taking falling damage, the health lost becomes a shield lasting 30 sec." },
      { 324441,  5, COVENANT_NECROLORD,  4, "Hearth Kidneystone", "Emeni",
        "You may attune your Hearth Kidneystone to any resting location and return to it. 12 hour cooldown, reduced by 5 min every killing blow." },
      { 323918,  5, COVENANT_NECROLORD,  7, "Gristled Toes", "Emeni",
        "Movement speed increased by 3% for every nearby enemy, up to 15%." },
      { 323919,  5, COVENANT_NECROLORD,  7, "Gnashing Chompers", "Emeni",
        "Gain 3% Haste for 10 sec after defeating an enemy, up to 15%." },
      { 323916,  5, COVENANT_NECROLORD,  7, "Sulfuric Emission", "Emeni",
        "When reduced below 20% health, you fear nearby enemies for 3.5 sec. May only occur once per 60 sec." },
      { 351089,  5, COVENANT_NECROLORD,  9, "Sole Slough", "Emeni",
        "After standing still for 5 sec, the next time you move you and nearby allies gain 20% increased movement speed for 10 sec." },
      { 351093,  5, COVENANT_NECROLORD,  9, "Resilient Stitching", "Emeni",
        "While above 90% health, you gain a shield that absorbs 3,699 magic damage for 1 min. This effect may only occur once every 1 min." },
      { 351094,  5, COVENANT_NECROLORD, 11, "Pustule Eruption", "Emeni",
        "Fleshcraft covers you in 3 pustules per 1 sec channeled. Taking damage or being healed pops a pustule, dealing 305 Nature damage to nearby enemies and healing nearby allies for 192 split between them." },
      // Necrolord / Bonesmith Heirmir
      { 326514, 10, COVENANT_NECROLORD,  0, "Forgeborne Reveries", "Bonesmith Heirmir",
        "Your Intellect and Armor are increased by 1% for each enchantment on your armor, up to 3%. | Upon death your armor anchors your soul, allowing you to fight for an additional 10 sec. During this time, your damage and healing done is reduced by 50% and you cannot receive healing. This effect can only occur once every 2 min." },
      { 326507, 10, COVENANT_NECROLORD,  2, "Resourceful Fleshcrafting", "Bonesmith Heirmir",
        "Fleshcraft's passive effect reduces the cooldown by an additional 1 sec when it consumes a corpse." },
      { 326504, 10, COVENANT_NECROLORD,  2, "Serrated Spaulders", "Bonesmith Heirmir",
        "Inflict 63 Shadow damage to your attacker over 5 sec when hit at melee range." },
      { 326512, 10, COVENANT_NECROLORD,  4, "Runeforged Spurs", "Bonesmith Heirmir",
        "Mounted movement speed is increased by 5%. If attacked while mounted, mounted movement speed is increased by an additional 10% for 30 sec." },
      { 326513, 10, COVENANT_NECROLORD,  4, "Bonesmith's Satchel", "Bonesmith Heirmir",
        "You have a chance to obtain a satchel of a bonesmith's preferred ore and gems when you kill an enemy that yields experience or honor." },
      { 326511, 10, COVENANT_NECROLORD,  7, "Heirmir's Arsenal: Gorestompers", "Bonesmith Heirmir",
        "Damaging or healing a target below 35% grants you 35% increased movement speed for 5 sec after you start moving. May only occur once per 1 min." },
      { 326572, 10, COVENANT_NECROLORD,  7, "Heirmir's Arsenal: Marrowed Gemstone", "Bonesmith Heirmir",
        "After landing 10 critical strikes, you gain 18% increased chance to critical strike for 10 sec. May only occur once per 60 sec." },
      { 326509, 10, COVENANT_NECROLORD,  7, "Heirmir's Arsenal: Ravenous Pendant", "Bonesmith Heirmir",
        "Defeating an enemy restores 3% of your maximum health every 6 sec for 6 sec, stacking up to 5 times. Adding stacks refreshes duration." },
      { 350899, 10, COVENANT_NECROLORD,  9, "Carver's Eye", "Bonesmith Heirmir",
        "Damaging an enemy above 90% health grants you 34 Mastery for 5 sec, up to 5 stacks. You cannot gain this benefit from the same target for 10 sec." },
      { 350935, 10, COVENANT_NECROLORD,  9, "Waking Bone Breastplate", "Bonesmith Heirmir",
        "When 3 or more enemies are nearby, your maximum health is increased by 5%. This effect lingers for 5 seconds." },
      { 350936, 10, COVENANT_NECROLORD, 11, "Mnemonic Equipment", "Bonesmith Heirmir",
        "When you damage an enemy that's below 35% health, 3% of the damage done is repeated over 5 sec.  | Healing an ally grants them the ability to have their damage repeat this way at 30% effectiveness for 5 sec. Limit 2." },
  };
  return t;
}

inline const entry_t* find( unsigned spell_id )
{
  for ( const auto& e : table() )
    if ( e.spell_id == spell_id )
      return &e;
  return nullptr;
}

inline const entry_t* find( std::string_view name )
{
  for ( const auto& e : table() )
    if ( name == e.name )
      return &e;
  return nullptr;
}

// The chosen soulbind traits, given as a slash separated list of spell ids or
// names, e.g. priest.legacy_soulbinds=328266/329778 or
// priest.legacy_soulbinds=combat_meditation/pointed_courage.
struct set_t
{
  std::string option;
  std::unordered_set<unsigned> chosen;

  void parse()
  {
    chosen.clear();
    std::string cur;
    auto flush = [ this, &cur ]() {
      if ( cur.empty() )
        return;
      bool numeric = cur.find_first_not_of( "0123456789" ) == std::string::npos;
      if ( numeric )
      {
        chosen.insert( static_cast<unsigned>( std::stoul( cur ) ) );
      }
      else
      {
        // Accept the snake_case form of the display name too. An
        // apostrophe is DROPPED rather than turned into a separator, so
        // "Kevin's Oozeling" is kevins_oozeling and not kevin_s_oozeling.
        // A trailing match is accepted as well, so the prefixed names
        // ("Heirmir's Arsenal: Marrowed Gemstone") can be given as just
        // marrowed_gemstone.
        for ( const auto& e : table() )
        {
          std::string n;
          for ( const char* p = e.name; *p; ++p )
          {
            char c = *p;
            if ( c == 0x27 )  // apostrophe
              continue;
            if ( c >= 'A' && c <= 'Z' )
              c = static_cast<char>( c - 'A' + 'a' );
            if ( ( c >= 'a' && c <= 'z' ) || ( c >= '0' && c <= '9' ) )
              n += c;
            else if ( !n.empty() && n.back() != '_' )
              n += '_';
          }
          while ( !n.empty() && n.back() == '_' )
            n.pop_back();
          bool exact  = n == cur;
          bool suffix = n.size() > cur.size() &&
                        n.compare( n.size() - cur.size(), cur.size(), cur ) == 0 &&
                        n[ n.size() - cur.size() - 1 ] == '_';
          if ( exact || suffix )
          {
            chosen.insert( e.spell_id );
            break;
          }
        }
      }
      cur.clear();
    };
    for ( char c : option )
    {
      if ( c == '/' || c == ',' || c == ' ' )
        flush();
      else if ( c >= 'A' && c <= 'Z' )
        cur += static_cast<char>( c - 'A' + 'a' );
      else
        cur += c;
    }
    flush();
  }

  bool has( unsigned spell_id ) const
  {
    return chosen.find( spell_id ) != chosen.end();
  }

  bool empty() const
  {
    return chosen.empty();
  }
};

}  // namespace legacy_soulbind
